version: "3"
services:
  vserver:
    image: "harbor.vantage6.ai/infrastructure/server:latest"
    volumes:
      - ./db/:/mnt/db/
      - ./server-config.yml:/mnt/config.yml
    command: vserver-local start -c /mnt/config.yml
    ports:
      - "5000:5000"
  vnode:
    container_name: vantage6-test-user
    depends_on:
      - vserver

    image: "harbor.vantage6.ai/infrastructure/node:latest"
    command: "vnode-local start -c /mnt/config/test.yml --dockerized"
    volumes:
      - ./node-config.yml:/mnt/config/test.yml
      - ./diabetes.csv:/mnt/database/database.csv
      - /var/run/docker.sock:/var/run/docker.sock
      - vnode-shared-volume:/mnt/data
      - ./id_rsa:/mnt/private_key.pem
    environment:
      - DATA_VOLUME_NAME=vnode-shared-volume
      - DATABASE_URI=/mnt/database/database.csv

  triplestore:
    image: djoerzilla/graphdb-free
    ports:
      - 7200:7200
    volumes:
      - ./triplestores/gp_organization:/mnt/config

volumes:
  vnode-shared-volume:
    name: vnode-shared-volume